name: "Hermes Agent"
slug: "hermes_agent"
version: "0.20.2"
description: "Pierwsza instancja Hermes Agent AI"
url: "https://github.com/swmyhome/hermes-agent-addon"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
options:
  HERMES_DASHBOARD: "true"
  username: "admin"
  password: "zmien-to-haslo-123"
schema:
  HERMES_DASHBOARD: str
  username: str
  password: password
schema_descriptions:
  HERMES_DASHBOARD: "Włącz panel dashboard Hermesa (true/false)"
  username: "Nazwa użytkownika do panelu Hermesa"
  password: "Hasło do panelu Hermesa"
ports:
  9119/tcp: 9120
ports_description:
  9119/tcp: "Port interfejsu Web UI Hermesa"
map:
  - config:rw
